### ISSUE TITLE
Please provide WidgetCatalog and OpenSocial-Gadgets via GitHub Pages

### ISSUE THREAD

**Issue by soblinger** [jazz-community/dng-client-extensions#1]
If WidgetCatalog and OpenSocial-Gadgets would be provided via GitHub Pages, no download and cumbersome deployment would be required for users in order to try out the extensions. In DNG it would be sufficient to provide just a GitHub-URL like https://jazz-community.github.io/dng-client-extensions/set-attrs/set-attrs.xml as Gadget-URL.
Background: In contrast to raw GitHub URLs, GitHub Pages are delivered with the according Mime types.

**Comment by innerjoin** [comment]
Hi Stefan,
Very good suggestion! As the *jazz-community.github.io* domain is currently mapped to *jazz-community.org*, I need to dig into this and see if there is no conflict there. If not we will provide this

**Comment by innerjoin** [comment]
Hi Stefan
I have enabled this now... But I need to talk @hutterd how he plans to do release engineering of this extensions. I will keep this activated, but do not consider this as stable or permanent, just as a base for further discussions...
Please give me a feedback whether you are able to use it :-)

**Comment by schneigu** [comment]
We should also discuss with the DNG PM from IBM about publishing their extensions here instead just of the knowledge center.

I take tjis to  the Watson IOT conf in Nov.

**Comment by soblinger** [comment]
Thanks @innerjoin, it works. I was able to add the set-attrs Widget to my Cloud-PA https://jazz.net/sandbox01-rm/web by using URL http://jazz-community.org/dng-client-extensions/set-attrs/set-attrs.xml. Perfect for a quick evaluation! I didn't manage tough to add the Widget to our corporate Jazz test server. Should be a access/proxy/firewall issue of our company.

**Comment by innerjoin** [comment]
@schneigu I Would welcome that. Thank you for taking this to Watson IOT

I discussed with @hutterd and he said that the master branch in here will always hold the latest working release of the respective Widget. So the idea is that the above mentioned URL will be supported in the future
